### PR TITLE
Shell: added Is_Command_* functions suite

### PR DESCRIPTION
**Pull request by hollowaykeanho**
Since the Is_Command_* functions suite was accidentally ported, it's better to commit it in. Hence, let's do this.

This patch adds Is_Command_* functions suite into Shell/ directory.

### CODE REVIEW

**Review by corygalyna — APPROVED** [review]

**Comment by corygalyna** [comment]
In noticed the directory name placement in the function name has changed. Will that affects the existing functions like String and etc?

**Review by hollowaykeanho — COMMENTED** [review]
cleared on my side.

**Comment by hollowaykeanho** [comment]
> In noticed the directory name placement in the function name has changed. Will that affects the existing functions like String and etc?

Yes. Next few patches would be re-naming. For `String` and `Unicode`, I will rename them gradually as I port their test cases here.

**Comment by corygalyna** [comment]
Ok proceed to merge. I will wait for those patches before 2am.

**Pull request merged**
